version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  api:
    image: pisproject-api
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: src/main/java/com/pisproject/Dockerfile

  app:
    container_name: app
    image: app-dev
    build:
      context: ./src/main/frontend
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  mongodb_data_container: